server:
  port: 9092
spring:
  application:
    name: a-second
  output:
    ansi:
      enabled: always
grpc:
  server:
    port: 12122
#management:
#  endpoints:
#    metrics:
#      enabled: true
#    info:
#      enabled: true
#    web:
#      exposure:
#        include: "*"